services:
    db:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: ws404db
            MARIADB_USER: ws404
            MARIADB_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_USER: ws404
            PMA_PASSWORD: password
        ports:
            - 8401:80
