services:
    db:
        image: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: ws404db
            MARIADB_USER: ws404
            MARIADB_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - ./db:/var/lib/mysql
